server:
  registryAddress: 127.0.0.1:8848?namespace=35a965ca-970d-412b-aa59-ed2bbcfcc22e
  serverAddr: ws://127.0.0.1:8878/im
  id: 1
  version: 1.0.0
  group: lyzzcw
  weight: 1

#LOG
log:
  level: DEBUG
logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: zim-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
cache:
  type:
    local: guava
    distribute: redis
distribute:
  type:
    enable: true
    # single or cluster
    arrange: single
    lock: redisson
    semaphore: redisson
websocket:
  enable: true
  port: 8878
  heartbeat:
    count: 10

rocketmq:
  namesvr: 192.168.3.48:9876
