server:
  port: 8090
  servlet:
    context-path: /router

#LOG
log:
  level: INFO
logging:
  config: classpath:logback-spring.xml

spring:
  # swagger3.0 与 srpring boot 2.6.x 冲突启动失败问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/zim?useUnicode=true&characterEncoding=utf8&useSSL=false
    # 连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM user
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
  minio:
    endpoint: http://192.168.3.48:9000
    visitPath: http://192.168.3.48:9000
    accessKey: lyzzcw
    secretKey: lyzzcw123
    region: acer-win
cache:
  type:
    local: guava
    distribute: redis
distribute:
  type:
    enable: true
    # single or cluster
    arrange: single
    lock: redisson
    semaphore: redisson

rocketmq:
  namesvr: 192.168.3.48:9876
mybatis:
  #  classpath:/com/*/*/mapper/*Mapper.xml 放在resources目录下classpath:/mapper/**.xml
  mapper-locations: classpath:/mapper/**.xml
#  type-aliases-package: com.example.demo.domain
  configuration:
    # 启动结果集自动映射（NONE,PARTIAL,FULL）
    auto-mapping-behavior: partial
    # 驼峰映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


